### ISSUE TITLE
MODE 7 display bug

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#126] opened 2016-09-24 22:45 UTC
"A very small bug. I think. In mode 7 if you set R9 of the 6845 to 31 and display an "A". You get the full "A" but then the top of "B" where are it should I think be the top of "A" . The SAA5050 should should count hsync pulses to work out which row of a character to display and not sneak a look at the 6845  :)"

Via http://stardot.org.uk/forums/viewtopic.php?p=149906

( @richtw1 any thoughts? )

**Comment by kieranhj** [comment] 2017-01-18 21:14
Here's another sample case for you: http://stardot.org.uk/forums/viewtopic.php?f=53&t=12436.  The ssd from the top of the thread looks fine in jsbeeb but missing lots of pixels on real hardware.

**Comment by scarybeasts** [comment] 2019-10-22 23:39
Kieran's test case looks like it actually got worse in recent jsbeeb (b-em is better for example), so definitely some investigation still needed here.

**Comment by mattgodbolt** [comment] 2019-10-23 03:58
zoiks!

**Comment by scarybeasts** [comment] 2019-11-06 21:14
[mode7-75.zip](https://github.com/mattgodbolt/jsbeeb/files/3816753/mode7-75.zip)

**Comment by scarybeasts** [comment] 2019-11-08 02:02
Didn't mean to close this.

**Comment by scarybeasts** [comment] 2019-11-08 02:04
There's hope: looks like b2 gets Kieran's test case correct, missing scanlines and all, and we understand the difference in SAA5050 <-> 6845 modeling between b2 and jsbeeb. We've confirmed b2's modeling is correct by scoping which pins are connected and how.

**Comment by scarybeasts** [comment] 2019-11-08 09:36
This PR makes things a bit better: https://github.com/mattgodbolt/jsbeeb/pull/292

Stuff that's fixed:
1) ?&FE00=9:?&FE00=24
Kind of flickery (probably not hitting R7/vsync) but the extra scanlines now correctly show a repeat of the "A" character if you do CLS then type AAAAAA.

2) ?&FE00=8:?&FE01=&90:?&FE00=9:?&FE01=9
This is no-interlace MODE 7, and it now works and even renders the incorrectly rounded characters the same as real hardware, showing we've likely wired up RA0 to CRS correctly.

**Comment by scarybeasts** [comment] 2019-11-08 09:36
![mode7noninterlace](https://user-images.githubusercontent.com/26288899/68465875-28557e80-01c8-11ea-95a2-d86c4e7b4911.png)

Attaching an image of no-interlace MODE 7 for gits and shiggles.

**Comment by scarybeasts** [comment] 2019-11-09 20:44
Also landed: https://github.com/mattgodbolt/jsbeeb/pull/293

This fixes: ?&FE00=6:?&FE01=100

Still no joy with Kieran's teletext ssd of doom.

**Comment by scarybeasts** [comment] 2019-11-10 08:37
mode7-75.ssd regressed with https://github.com/mattgodbolt/jsbeeb/pull/278, a change that fixes some pretty wayward (any easily measurable) interlace timing, so time to put the thinking cap on!!!

**Comment by scarybeasts** [comment] 2019-11-13 06:29
Also landed: https://github.com/mattgodbolt/jsbeeb/pull/294

Kieran's teletext ssd of doom is now acceptable; better than it's ever been. Screenshots to follow.

**Comment by scarybeasts** [comment] 2019-11-13 06:32
![parrot_jsbeeb](https://user-images.githubusercontent.com/26288899/68738842-39253c00-059c-11ea-8a0b-5e4aa51b1970.png)

That's jsbeeb's current render of the parrot. Note that the missing black chunks are actually a correct emulation. Older jsbeeb rendered a "whole" parrot but that didn't match real hardware.

**Comment by scarybeasts** [comment] 2019-11-13 06:35
![parrot_real_hw](https://user-images.githubusercontent.com/26288899/68738966-830e2200-059c-11ea-8d9f-a30d39bbfb3c.jpg)

That's Kieran's original screenshot from real hardware. Looks the same on the beeb model 3 I have.

jsbeeb isn't perfect -- there's a thin black scanline about a third of the way down on real hardware which is unexplained. But I think we're good enough to mark this issue as fixed since MODE 7 + CRTC hijinks is much much more accurate now.

**Closed by scarybeasts** 2019-11-13 06:35 UTC
Labels: video
