### ISSUE TITLE
Games that don't work in JSBeeb

### ISSUE THREAD

**Issue by ahope1** [mattgodbolt/jsbeeb#140] opened 2016-12-16 15:28 UTC
I wanted to try to list all games that are known _not_ to work in JSBeeb, in the hope that the info is useful for future development (and isn't just annoying!).

---

**Games that don't work because of possible timing issues in JSBeeb**

**_Uridium_**
Link: http://bbcmicro.co.uk/game.php?id=557
Info: https://github.com/mattgodbolt/jsbeeb/issues/130

~~**_Terra Australis_**~~
~~Link: [on bbc.godbolt.org](http://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/t4t55k1ukf1hqbt/TERRAA.SSD)~~
~~Info: https://github.com/mattgodbolt/jsbeeb/issues/125#issue-176777425~~

~~**_Ghouls Of Azzod_**~~
~~Link: [on bbcmicro.co.uk](http://bbcmicro.co.uk/jsbeeb/play.php?disc=http://bbcmicro.co.uk//gameimg/discs/599/Disc034-GhoulsOfAzzod.ssd&autoboot)~~
~~Info: [on Stardot](http://stardot.org.uk/forums/viewtopic.php?f=51&t=12387&p=189541#p189572)~~
~~Workaround: [insert *EXEC !BOOT into kbd buffer with patch](http://bbcmicro.co.uk/jsbeeb/play.php?disc=http://bbcmicro.co.uk//gameimg/discs/599/Disc034-GhoulsOfAzzod.ssd&patch=@bc09,3e0:2a455845432021424f4f540d;@bc09,2d8:e0;@bc09,2e1:ec)~~

**_Dragonsoft Explorer_**
Link: [on bbc.godbolt.org](https://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/2g55rr6qhv1vg80/PLAY_DISC.ssd&disc2=https://dl.dropboxusercontent.com/s/9zeyr1zotxw5v35/SAVE_DISC.ssd)
Info: [on Stardot](http://www.stardot.org.uk/forums/viewtopic.php?f=1&t=598&p=188387#p188383)

**_The Attic Bug in SameGame_**
Link: http://bbcmicro.co.uk/game.php?id=1891
Info: [on Stardot](http://www.stardot.org.uk/forums/viewtopic.php?f=51&t=14246)

**_Get Set Santa_**
Link: [on bbcmicro.co.uk](http://bbcmicro.co.uk/jsbeeb/play.php?disc=http://bbcmicro.co.uk//gameimg/discs/1410/Disc079-GetSetSantaE.ssd&autoboot)
Info: [on Stardot](http://stardot.org.uk/forums/viewtopic.php?f=51&t=12387&p=189541#p189572)
Workaround: [insert *EXEC !BOOT into kbd buffer with patch](http://bbcmicro.co.uk/jsbeeb/play.php?disc=http://bbcmicro.co.uk//gameimg/discs/1410/Disc079-GetSetSantaE.ssd&patch=@bc09,3e0:2a455845432021424f4f540d;@bc09,2d8:e0;@bc09,2e1:ec)

**_Mystery of the Java Star_**
Link: [on Stardot](https://stardot.org.uk/forums/viewtopic.php?f=1&t=15714#p215251)
Info: Game freezes up at start of Chapter 2. (You can skip Chapter 1 and go straight to Chapter 2 if you want to see for yourself.)

---

**Games that don't work because they attempt to read disc-sector headers**

**_Puff_**
Link: [on bbcmicro.co.uk](http://bbcmicro.co.uk//jsbeeb/play.php?autoboot&disc=/play.php?autoboot&disc=http://bbcmicro.co.uk//gameimg/discs/2195/Disc999-Puff-1.ssd) (try to start a new game)
Info: [on Stardot](http://stardot.org.uk/forums/viewtopic.php?f=51&t=15088&p=203176#p203176)
Workaround: [boot in Master mode](http://bbcmicro.co.uk//jsbeeb/play.php?autoboot&disc=/play.php?autoboot&disc=http://bbcmicro.co.uk//gameimg/discs/2195/Disc999-Puff-1.ssd&model=Master)

---

**Games that don't work because they need DFS 1.2**

**_Oddjob_**
Link: [on bbcmicro.co.uk](http://bbcmicro.co.uk/jsbeeb/play.php?disc=http://bbcmicro.co.uk//gameimg/discs/1849/Disc103-OddJobD.ssd&autoboot)
Info: https://github.com/mattgodbolt/jsbeeb/issues/46#issuecomment-267388069
Workaround: [load DNFS using @patch](http://bbcmicro.co.uk/jsbeeb/play.php?disc=http://bbcmicro.co.uk//gameimg/discs/1849/Disc103-OddJobD.ssd&disc2=http://bbcmicro.co.uk//gameimg/discs/1849/OddJobWA.ssd&patch=@bc09,3e0:2A445249564520310D2A455845432021424F4F540D;@bc09,2d8:e0;@bc09,2e1:f5)

---

**Games that don't work possibly because they need Sideways RAM in Model B mode**

**_Dunjunz_**
Link: http://bbcmicro.co.uk/game.php?id=1068
Info: [below](https://github.com/mattgodbolt/jsbeeb/issues/140#issuecomment-267735533), and [on Stardot](http://www.stardot.org.uk/forums/viewtopic.php?f=51&t=12277&p=156383#p156383), and [below again](https://github.com/mattgodbolt/jsbeeb/issues/140#issuecomment-267820763)
Update: http://www.stardot.org.uk/forums/viewtopic.php?f=1&t=13214&p=172123#p172123

---

**Games that don't work possibly because they need a ROM in a write-protected Sideways RAM slot**

[Moved Dragonsoft Explorer to the "timing issues" section, above]

---

~~**Games that don't work because they need write-access to the game disc**~~

~~**_Zen_**~~
~~Link: [on bbcmicro.co.uk](http://bbcmicro.co.uk/jsbeeb/play.php?autoboot&disc=http://bbcmicro.co.uk/gameimg/discs/1992/Disc111-ZenSTD.ssd)~~

~~**_Pop Quiz Master (Database Disc 1)_**~~
~~Link: [on bbcmicro.co.uk](http://bbcmicro.co.uk/jsbeeb/play.php?autoboot&disc=http://bbcmicro.co.uk/gameimg/discs/Disc999-PopQuizMaster.ssd&disc2=http://bbcmicro.co.uk/gameimg/discs/Disc999-PopQuizMasterDatabaseDisc1.ssd)~~
~~Info: [on Stardot](http://www.stardot.org.uk/forums/viewtopic.php?f=51&t=12277#p156258)~~
~~Also:~~
~~**_Pop Quiz Master (Database Disc 2)~~
~~Pop Quiz Master (Database Disc 3)~~
~~Pop Quiz Master (Database Disc 4)_**~~

~~**_Pip's Island Adventure_**~~
~~Info: [on Stardot](http://www.stardot.org.uk/forums/viewtopic.php?f=2&t=6876#p189520)~~

**Comment by mattgodbolt** [comment] 2016-12-16 16:49
This is great: thanks!

**Comment by ahope1** [comment] 2016-12-17 01:55
Added Dunjunz to the list above, speculating that it fails because of a lack of Sideways RAM in Model B mode in JSBeeb. Am I correct?

**Comment by BigEd** [comment] 2016-12-17 07:26
I see Dunjunz fails in a different way if you add
model=master
to the URL. If the game needs sideways RAM, is Master the right option? Or does it really need a Beeb with sideways RAM? That would be a third-party option...

**Comment by ahope1** [comment] 2016-12-17 13:09
@BigEd I think it needs a Beeb with Sideways RAM ([more info](http://www.stardot.org.uk/forums/viewtopic.php?f=51&t=12277&p=156383#p156406)).

Actually, Model B mode in JSBeeb does seem to provide Sideways RAM, so maybe it's not in the right slots for Dunjunz?:

http://bbc.godbolt.org/?autoboot&disc=https://dl.dropboxusercontent.com/s/tbuoek1geoq0dg9/SWRAMtricky.ssd&rom=https://dl.dropboxusercontent.com/s/ocqrpii2qkbf2xs/ARM100.ROM

**Comment by BigEd** [comment] 2016-12-17 13:28
Ah, good spot. I see the code here:
https://github.com/mattgodbolt/jsbeeb/blob/191fe8993b8be63c8c341b046ee9223a56722d81/models.js#L14
So we have different swram banks in beeb mode and master mode.

**Comment by ahope1** [comment] 2016-12-17 13:57
Aha! Thanks for the link to the hardcoded SWRAM slots. Would it break Exile and/or Dunjunz if *all* possible ROM/RAM slots (apart from the ones for BASIC and a DFS) were made available as SWRAM?

**Comment by Pernod70** [comment] 2016-12-17 14:15
For games like Exile, Dunjunz, UIM, Holed Out, etc. why are we not just running them in Master mode? They were intended for Master or BBC with SWRAM, so instead of hacking them to work with whatever SWRAM configuration we may have in B mode just run them as intended on a Master.

**Comment by ahope1** [comment] 2016-12-17 15:26
@Pernod70 I don't think we're trying to hack the actual _games_. 

Rather, we're suggesting that Matt might be able to make JSBeeb more configurable, probably via more URL params, so that we can create instances of JSBeeb with different SWRAM slots available, or different DFS versions, etc.

Re Dunjunz, as BigEd commented above, in JSBeeb it doesn't work in Master mode either! So something in JSBeeb does seem to need changing.

**Comment by mattgodbolt** [comment] 2016-12-17 16:13
Thanks everyone for the lively discussion. As you can tell from the comment in the `model.js` file, along with #137 I've realised the current set up isn't perfect. In fact the whole thing was set up the way it is primarily so I can play Exile on the default "BBC B" settings :-)

I'm very much against patching games etc, but very much in favour of having more choice in the model selection (DFS versions, sideways RAM, ROMs etc).

The issue with Dunjunz appears to be something else that I'll need to dig further in to.

**Comment by ahope1** [comment] 2016-12-18 13:19
Yeah, I'm no longer sure that Dunjunz fails in JSBeeb because of SWRAM issues. If Dunjunz can't find suitable SWRAM slots, it normally prints up this message and then quits:

![Dun](https://dl.dropboxusercontent.com/s/u34iy8lsvdf2b10/Dunjunz1.png)

That message _isn't_ displayed in JSBeeb, so it looks like Dunjunz _is_ able to find suitable SWRAM in JSBeeb..?

**Comment by pau1ie** [comment] 2016-12-19 11:50
@Pernod70 - I am making changes so http://bbcmicro.co.uk can run games in master mode; actually so you can pass custom parameters to jsbeeb per disc image. It is still in progress. Hopefully I will get some time over the holidays to complete this work. I suspect the result of this and #112 will result in a number of disc images that require custom boot parameters.

**Comment by ahope1** [comment] 2017-07-12 12:50
Added [an entry](https://github.com/mattgodbolt/jsbeeb/issues/140#issue-196084350) for DragonSoft Explorer, which I think needs a write-protected Sideways ROM slot:

http://stardot.org.uk/forums/viewtopic.php?f=1&t=598&p=175066#p175066

**Comment by mattgodbolt** [comment] 2017-07-12 12:55
Thanks for the update @ahope1

**Comment by ahope1** [comment] 2017-07-12 13:04
Thanks, @mattgodbolt 

I've also updated the entry for Dunjunz, as I've now found a version of Dunjunz that _does_ seem to work in JSBeeb:

http://www.stardot.org.uk/forums/viewtopic.php?f=1&t=13214&p=172123#p172123

**Comment by ahope1** [comment] 2017-12-09 21:57
Updated the first post in this thread to move Dragonsoft Explorer because it still doesn't work in JSBeeb, even though someone has now produced a version of it that doesn't need a write-protected ROM.

**Comment by mattgodbolt** [comment] 2017-12-10 15:19
Thanks @ahope1 . I really hope I can find time to look in to some of these!

**Comment by ahope1** [comment] 2017-12-19 18:44
@mattgodbolt Updated [the first post](https://github.com/mattgodbolt/jsbeeb/issues/140#issue-196084350) again because a new failing game has been discovered: "Attic Bug In The SameGame".

**Comment by ahope1** [comment] 2017-12-22 13:17
Another update of [the first post](https://github.com/mattgodbolt/jsbeeb/issues/140#issue-196084350) in this thread, to mention Get Set Santa.

**Comment by ahope1** [comment] 2017-12-22 18:18
Updated again to add Pip's Island Adventure because it needs write access to the disc. It would be really useful if there were a URL parameter that we could pass to enable writing to the local in-browser cached copy of a disc-image.

**Comment by BigEd** [comment] 2017-12-22 18:21
It starts to look like we need some sort of triage or categorisation
- broken because needs writes access
- broken because bad OS ROM assumption
- broken because bad cycle timing in emulation
- broken because assumes something about initial RAM state
and so on.

**Comment by ahope1** [comment] 2017-12-22 18:56
@BigEd Erm, have you seen [the post at the top of this thread](https://github.com/mattgodbolt/jsbeeb/issues/140#issue-196084350)?

**Comment by BigEd** [comment] 2017-12-22 19:09
ahem.  Yes I have now! I'll delete my ignorant comment...

**Comment by mattgodbolt** [comment] 2018-02-07 14:26
As of change 5b9135f discs are read/write by default (losing changes silently on window close). Hopefully that fixes up the first group of games.

**Comment by ahope1** [comment] 2018-02-10 01:30
@mattgodbolt Thanks, Matt! That's great. Any chance you could make disc-drive noises optional too? That would be ideal for bbcmicro.co.uk, which currently uses an earlier version of JSBeeb which doesn't implement the noises and thus loads games "instantly"!

**Comment by ahope1** [comment] 2018-05-14 18:38
Updated [first post in this thread](https://github.com/mattgodbolt/jsbeeb/issues/140#issue-196084350) to add details about Puff, another game that doesn't work in JSBeeb.

**Comment by ahope1** [comment] 2018-05-16 09:25
I've been told that it might be attempts to do direct sector reads that cause Puff to fail in JSBeeb, rather than timing issues:

http://stardot.org.uk/forums/viewtopic.php?f=51&t=15088&p=203176#p203190

**Comment by ahope1** [comment] 2018-09-21 17:16
Updated [first post in this thread](https://github.com/mattgodbolt/jsbeeb/issues/140#issue-196084350) to add details about Mystery Of The Java Star, another game that doesn't work in JSBeeb. (But it _does_ work in BeebEm.)

**Comment by ahope1** [comment] 2019-07-30 17:48
Deleted the game Terra Australis from [the list](https://github.com/mattgodbolt/jsbeeb/issues/140#issue-196084350) because it seems to have been [fixed](https://github.com/mattgodbolt/jsbeeb/issues/125) (but only as a side-effect of one of the latest updates to JSBeeb?).

I've also deleted Ghouls Of Azzod because it's suddenly started working, even in the old version of JSBeeb that's installed on bbcmicro.co.uk -- which hasn't changed since before I originally reported this bug! No idea how it can suddenly start working when nothing's changed!

I should probably delete Get Set Santa too becuase it too seems to work in the old version of JSBeeb on bbcmicro.co.uk. What's holding me back is that it works for me on macOS Mojave (10.14) but _not_ on macOS Yosemite (10.10). No idea why. It's all very confusing!

**Comment by scarybeasts** [comment] 2019-07-30 21:32
@ahope1 @mattgodbolt 

Can we close this bug? I find it a bit confusing to have a megabug open for so many games and to have the list change.

Let's open one bug for every game still with problems and I will try and fix them all. Some notes:

- There are two bugs already open for Uridium and I will continue investigation there.
- Puff looks interesting. In non-Master mode it appears to be some i8271 disc thing that BeebEm can handle so jsbeeb should be able to as well. The issue has my curiosity so I will take it on next and I can file the Puff bug. (It also fails on my i8271-only nascent emulator so I need to understand it :)

**Comment by scarybeasts** [comment] 2019-07-31 02:44
Regarding Puff, I'm not going to open a new bug for it just yet because it looks like a DFS-0.9 vs. DFS-1.2 issue:

- BeebEm, DFS-1.2 (default) works.
- BeebEm, DFS-0.9 fails.
- B-em, DFS-0.9 (default) fails.
- B-em, DFS-1.2 works.

And they have different lineage i8271 drivers best I can tell.

I'll see if someone on Stardot can try Puff on a real DFS-0.9 beeb.

**Comment by scarybeasts** [comment] 2019-07-31 04:25
Actually, investigating a bit more, it looks like a problem with the Puff disc. In an effort to work around a "No room" out-of-memory type error, the loader sets page to &1700. This is going to trample some of the DFS work space, no? I think DFS-0.9 is within its rights to not work!
I'll move on.

**Comment by scarybeasts** [comment] 2019-07-31 04:36
The Attic Bug in SameGame now works on https://bbc.godbolt.org/ (and still fails on bbcmicro.co.uk) -- yay.

**Comment by scarybeasts** [comment] 2019-07-31 06:17
The Dragonsoft Explorer failure is real. Filed as https://github.com/mattgodbolt/jsbeeb/issues/198

**Comment by scarybeasts** [comment] 2019-07-31 06:51
Get Set Santa on bbcmicro.co.uk now has a patch in the URL but take it out:
http://bbcmicro.co.uk//jsbeeb/play.php?disc=http://bbcmicro.co.uk//gameimg/discs/1410/Disc079-GetSetSantaE.ssd&autoboot
... and you get the black boot screen failure.

I can't reproduce this locally, game autoboots fine, so it appears fixed?

**Comment by scarybeasts** [comment] 2019-07-31 07:00
I can't reproduce the Mystery of the Java Star failure: "Game freezes up at start of Chapter 2". It works for me on bbcmicro.co.uk. Anyone else?
http://bbcmicro.co.uk/game.php?id=2897

**Comment by scarybeasts** [comment] 2019-07-31 08:29
The Dunjunz failures appear to be simple sideways RAM bank configuration issues. Split that issue out for a decision:
https://github.com/mattgodbolt/jsbeeb/issues/199

**Comment by scarybeasts** [comment] 2019-07-31 08:30
I think we can close this bug now?

**Comment by lurkio** [comment] 2019-07-31 09:30
> Get Set Santa on bbcmicro.co.uk now has a patch in the URL but take it out:
> http://bbcmicro.co.uk//jsbeeb/play.php?disc=http://bbcmicro.co.uk//gameimg/discs/1410/Disc079-GetSetSantaE.ssd&autoboot
> ... and you get the black boot screen failure.
> 
> I can't reproduce this locally, game autoboots fine, so it appears fixed?

The disc-image does appear to work in the latest version of JSBeeb on bbc.godbolt.org, yes.

**Comment by ahope1** [comment] 2019-07-31 19:10
> I think we can close this bug now?

As I'm now unable to reproduce the Uridium bug in the latest version of JSBeeb, and as I've checked and thumbsed-up your comments about Attic Bug SameGame, Java Star, Dunjunz, Get Set Santa, and Dragonsoft Explorer, I think we should probably close this bug, yes.

The jury's still out on Puff, but I guess we can always open a new issue if it turns out it works on a real Beeb with DFS0.9.

**Closed** 2019-07-31 19:11 UTC
Labels: bug

**Comment by mattgodbolt** [comment] 2019-07-31 19:39
Thanks both!
