### ISSUE TITLE
Option for shift-break on menu + url

### ISSUE THREAD

**Issue by stuaxo** [mattgodbolt/jsbeeb#80] opened 2015-08-29 12:12 UTC
This way we can share URLs that load a disk image.

**Comment by stuaxo** [comment] 2015-08-29 12:18
Ah, just found "autoboot" - it would be great if this was an extra button on the load disk image dialog.

**Comment by mattgodbolt** [comment] 2015-08-30 16:38
Mostly a duplicate of #39 ... will fix!

**Closed by mattgodbolt** 2015-08-30 16:38 UTC

**Comment by mattgodbolt** [comment] 2015-08-30 19:23
Done and site updated. Thanks for the suggestion!

On Sat, Aug 29, 2015 at 7:18 AM, Stuart Axon <notifications@github.com>
wrote:

> Ah, just found "autoboot" - it would be great if this was an extra button
> on the load disk image dialog.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/jsbeeb/issues/80#issuecomment-135980190>.
>



-- 
Matt
