### ISSUE TITLE
Sampled sound demo fails in JSBeeb

### ISSUE THREAD

**Issue by ahope1** [mattgodbolt/jsbeeb#122] opened 2016-08-30 10:02 UTC
https://bitshifters.github.io/posts/archives/tyb-enjoy.html

See link. Sound isn't output correctly. Compare BeebEm. 

(I'm on OS X 10.10.5. Demo fails in both Safari and Chrome browsers.)

**Comment by mattgodbolt** [comment] 2016-08-30 13:19
I agree the sound isn't great. I presume the same demo works OK on a real Master? Will dig some on my side too: there seems to be a hardware-specific issue with how many cycles the chip write-enable needs to be low to actually get it to work (which Repton 2/Speech (ab)use): I picked 14 as that seems consistent with the hardware docs but that could be too low.  (https://github.com/mattgodbolt/jsbeeb/commit/cf0790dfd67621ebac7e0b00cb6c4d5a57286aec)

Of course, it may not be that. Will have a poke around. Do you know what technique it's using to play the sound?

**Comment by ahope1** [comment] 2016-08-30 13:24
Afraid I don't know the technique, and I suspect I wouldn't understand if someone told me!

The technique may or may not -- but more likely not -- be similar to the one used for another demo on the following page, which says, "All of the VGM files were ported to BBC Micro using a conversion script that transposes VGM files captured on an NTSC SN76489 to be frequency compatible with a 4Mhz BBC Micro SN76489": https://bitshifters.github.io/posts/prods/bs-beebtracker1.html

**Comment by ahope1** [comment] 2016-08-30 13:24
Kieran is the chap who might know -- he runs the site and made the new demos on there. He was on Stardot today: http://www.stardot.org.uk/forums/viewtopic.php?f=2&t=11731

**Comment by mattgodbolt** [comment] 2016-08-30 13:26
Thanks :) I know Kieran :)

**Comment by ahope1** [comment] 2016-08-30 13:29
Ah, good! 

Btw, the first demo I linked to (Enjoy The Silence) runs on a Model B too. (In BeebEm. Haven't tried on any real hardware yet.)

**Comment by mattgodbolt** [comment] 2016-08-30 13:32
Oh perfect. I thought from the title page ("85 1/4K Master/Compact
megamix") that it was Master only. ta!

**Comment by sassquad** [comment] 2016-08-30 21:24
@ahope1 @mattgodbolt Wow, these bring back memories - weren't these demos on the Fast Access disk subscription magazine? In any case, these and the Daniel Pugh tracks are awesome!

**Comment by scarybeasts** [comment] 2019-07-28 22:41
Duplicate of #167

**Comment by scarybeasts** [comment] 2019-07-28 22:41
@mattgodbolt Can you close?

**Closed** 2019-07-29 12:43 UTC
Labels: audio

**Comment by sitsofe** [comment] 2021-04-04 18:49
(@sassquad While trying to search for "Fast access enjoy the silence" I came across your comment. Thanks to you I've been able to track down Daniel Pugh's arrangement of Enjoy the Silence (e.g. see [Fast Access Volume 1](http://8bs.com/catalogue.htm#Fast%20Access%20Magazine%20Volume%201) Disk 6 or [Pernod's Music Collection "Music Disc Vol.3"](https://stardot.org.uk/forums/viewtopic.php?p=48398#p48398)) and thanks to JSBeeb I've been able to play it! It's an interpretation rather than the sampled version like the one at the bitshifters link but it was the one I was looking for. Thank you!)
