### ISSUE TITLE
Support "paste"

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/jsbeeb#164] opened 2018-02-11 19:44 UTC
Suggested over email, pasting snippets might be handy

**Comment by pau1ie** [comment] 2018-10-06 23:05
This looks like a duplicate of #86

**Comment by scarybeasts** [comment] 2019-08-22 06:51
@mattgodbolt I found myself fiddling around with what this might look like.

There's an unfinished CL I just uploaded on the "paste" branch. Aside from starting to experiment with paste, I also quite like the cleanup for sendRawKeyboardToBBC.

Before I continue with the CL, could I get some feedback on the following items?

- Do we still think paste is a worthwhile feature?
- What should the UX be? I've gone for paste to the main canvas item itself. This has the upside of being IMHO intuitive. Downsideos include that it's not obvious that it's there, and also that the browser context menu no longer offers the canvas "save image" options -- it offers the textarea "paste" instead. Depending on how we like these trade-offs, an alternate UX would be a paste dropzone right of the menu bar.
- Should I try cranking the keyboard harder? Paste of big snippets could be a little slow so I wonder if MOS could slurp keys a little faster. (Maybe it can't, IIRC it adds a lot of latency by waiting to do most work in the 100ms interrupt timer instead of the keyboard interrupt.)

**Comment by richtw1** [comment] 2019-08-22 07:12
Yes please add this!! I think you'll certainly be limited by the 100Hz timer, and I even think it waits for two ticks to process a key, though maybe I've misremembered.

You thinking of mapping it to a non BBC key, or via a UI element?

**Comment by richtw1** [comment] 2019-08-22 07:16
There's probably even a clever way to observe that a character has been consumed from the keyboard buffer, in order to give you max throughput. Think that in, e.g. Mode 2, each character is 32 bytes to display, and scrolling another 640 bytes to clear. Key presses might get lost if you went too fast.

**Comment by scarybeasts** [comment] 2019-08-22 07:34
@richtw1 There's unfinished code on the referenced branch:
https://github.com/mattgodbolt/jsbeeb/tree/paste

Paste is mapped to the HTML onpaste event for a textarea shadowing the main render canvas. This means you get "right click -> paste" provided by the browser. In my Linux laptop it's also super convenient to just hit the middle mouse button in the middle of the jsbeeb window.

There may be some downsides to that mapping though. In addition to the musings above, I haven't checked if there are colliding interests with CTRL+V.

**Comment by lurkio** [comment] 2019-08-24 17:54
@scarybeasts Neat. I've been testing this on iOS. It basically works, but there was an alarming moment when the text I'd copied to the iOS clipboard came out with its case inverted when I pasted it into JSBeeb! But I can't reproduce the effect. I might try again later.

**Closed** 2019-08-25 00:53 UTC

**Comment by scarybeasts** [comment] 2019-08-25 01:13
@lurkio You'll probably get inverted case if CAPS LOCK is off when you paste something. If it's a bother, it should be possible to address without diving too hard into the internals of the BBC state.

**Comment by lurkio** [comment] 2019-08-25 18:27
@scarybeasts:
> You'll probably get inverted case if CAPS LOCK is off when you paste something. If it's a bother, it should be possible to address without diving too hard into the internals of the BBC state.

Just tried again. Yes, the issue seems to be dependent on the state of the Caps Lock key. I take it you're toggling Caps Lock to switch case when pasting the text, then? 

Perhaps the state of Caps Lock and Shift Lock should be cached before the paste happens, then Caps Lock and Shift Lock should be reset, and then the paste can go ahead..?

**Comment by scarybeasts** [comment] 2019-08-28 21:58
Thanks @lurkio, landing a patch to do just that.
